### ISSUE TITLE
Not redirecting

### ISSUE THREAD

**Issue by Ps3mk18** [TW-D/DNS-Spoofing_WiFi-Pineapple-Mark-VII#2]
Im a completly dummy but.

i installed all files as told on my kali 

now i runned the main script it connected and worked just fine and "172.16.42.1 example.com" was added to the host file

if i now connect to my mark VII Wifi and try to open example.com i going to see the real page.

the host file does not redirect

and where can i find the template folder?

**Comment by TW-D** [comment]
Hi @Ps3mk18 , the "**example.com**" domain is different from the "**www.example.com**" domain, by default this program already has a template for the "www.example.com" domain **only**, so you will have to add an **"example.com" file** in the **"templates/" folder** containing the HTML/CSS/JS of your page.
